
[terminal.shell]
program = "/usr/bin/fish"

[font]
size = 12

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[font.bold]
family = "FiraCode Nerd Font"
style = "Bold"

[window]
opacity = 0.65
decorations = "none"

[window.padding]
x = 18
y = 18

[cursor]
style = "Beam"
#blink = true

[[keyboard.bindings]]
key = "Return"
mods = "Control|Shift"
action = "SpawnNewInstance"

[general]

live_config_reload = true
# =========================
# Alacritty Main Config
# Clean setup
# =========================

import = ["~/.config/alacritty/colors.toml"]
#import = ["~/.cache/wal/alacritty.toml"]
[terminal]
